channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - snakemake =5.20.1
  - mamba
  - pyyaml
  - yaml
  - pandas
  - pytest
  - click
  - shmlast >=1.6
  - ope >=0.8
  - khmer >=2.0
  - rich
  # these are for dag printing
  #- graphviz
  #- networkx
  #- pygments
  #- pygraphviz
  #- psutil
