dammit_dir: .dammit
db_dir: databases
logs_dir: logs
input_transcriptome: "test.fa"
report_file: dammit_annotation_report.rst

## last ##
lastal:
  output_suffix: 
    - .__database__.lastal.maf
    - .__database__.lastal.gff3
  databases:
    - uniprot_sprot
    - OrthoDB
    - uniref90
    - nr
  params:
    frameshift_cost: 15
    extra: ""
  
lastdb: 
  output_suffix: 
    - .fasta.prj
  params:
   extra: " -w3 "

## shmlast ##
shmlast:
  output_suffix:
    - .__database__.shmlast.csv
    - .__database__.shmlast.gff3
  databases:
    - userdb
  params:
    evalue: 1e-5
    extra: ""

## busco ##
busco:
  output_suffix: 
    - .__database__.busco.results
  databases:
    - BUSCO
  db_dir: busco2db
  params:
    extra: ""

## hmmer ##
hmmscan:
  output_suffix:
    - .__database__.hmmscan-domtbl.txt
    - .__database__.hmmscan.gff3
  databases:
    - Pfam-A
  params:
    extra: ""

hmmsearch:
  output_suffix:
    - .__database__.hmmsearch-domtbl.txt
    - .__database__.hmmsearch.gff3
  databases:
    - Pfam-A
  params:
    extra: ""

hmmpress:
  output_suffix:
    - .hmm.h3f
  params:
    extra: ""

## infernal ##
cmscan:
  output_suffix:
    - .__database__.cmscan-tblout.txt
    - .__database__.cmscan.gff3
  databases:
    - Rfam
  params:
    extra: ""

cmpress:
  output_suffix:
    - .cm.i1i
  params:
    extra: ""
  
## transdecoder ##
transdecoder_longorfs: 
  output_suffix:
    - .transdecoder_dir/longest_orfs.pep
  params:
    extra: "-m 80 "

transdecoder_predict:
  output_suffix:
    - .fasta.transdecoder.gff3
  params:
    extra: ""

# dammit utilities
rename_transcriptome:
  output_suffix:
    - .fasta
  params:
    extra: ""
