## dammit directories
database_dir: $HOME/.local/share/dammit/databases
temp_dir: $HOME/.local/share/dammit/temp
conda_env_dir: $HOME/.local/share/dammit/envs

# each program has a default evalue that is used if the global evalue isn't given
global_evalue: null

pipeline: default

basename: Transcript
rename: true
regex_rename: null

# n_threads: total threads to pass to snakemake -j
n_threads: 0
# max threads to use on a single job
max_threads_per_task: 1

verbosity: 0

busco_groups: 
  - metazoa_odb10

## last ##
lastal:
  params:
    evalue: 0.00001
    frameshift_cost: 15
    extra: ""
  
lastdb: 
  params:
   extra: " -w3 "

## shmlast ##
shmlast:
  params:
    evalue: 1e-5
    extra: ""

## busco ##
busco:
  configfile: busco.default.ini
  params:
    evalue: 1e-3
    extra: ""

## hmmer ##
hmmscan:
  params:
    evalue: 0.00001
    extra: ""

hmmpress:
  params:
    extra: ""

## infernal ##
cmscan:
  params:
    evalue: 0.00001
    extra: "--nohmmonly"

cmpress:
  params:
    extra: ""
  
## transdecoder ##
transdecoder_longorfs: 
  params:
    extra: "-m 80 "

transdecoder_predict:
  params:
    extra: ""

# dammit utilities
rename_transcriptome:
  params:
    extra: ""
